from app.main import app


def test_openapi_schema_includes_analytics_route() -> None:
    schema = app.openapi()

    assert "/api/auth/refresh" in schema["paths"]
    assert "/api/auth/logout" in schema["paths"]
    assert "/api/statistics/analytics" in schema["paths"]
    assert "/api/social/feed" in schema["paths"]
    assert "/api/social/people/{user_id}/follow" in schema["paths"]
    assert "/api/social/leaderboard" in schema["paths"]
    assert "/api/social/posts/{post_id}/comments" in schema["paths"]
    assert "/api/social/notifications" in schema["paths"]
    assert "/api/social/challenges" in schema["paths"]
    assert "/api/social/challenges/{challenge_id}/join" in schema["paths"]
    assert "/api/social/commitments" in schema["paths"]
    assert "/api/social/tasks/{task_id}/accountability" in schema["paths"]
    assert "/api/gamification" in schema["paths"]
    assert "/api/groups" in schema["paths"]
    assert "/api/groups/join" in schema["paths"]
    assert "/api/groups/{group_id}/invitations" in schema["paths"]
    assert "/api/groups/{group_id}/tasks" in schema["paths"]
    assert "/api/groups/tasks/{task_id}" in schema["paths"]
    assert "/api/groups/{group_id}/milestones" in schema["paths"]
    assert "/api/groups/{group_id}/progress" in schema["paths"]
    assert "/api/groups/{group_id}/activity" in schema["paths"]
    assert "/api/groups/{group_id}/analytics" in schema["paths"]
    assert "/api/groups/{group_id}/challenges" in schema["paths"]
    assert "/api/groups/{group_id}/achievements" in schema["paths"]
    assert "/api/groups/challenges/{challenge_id}" in schema["paths"]
    assert "/api/groups/activity/{activity_id}/comments" in schema["paths"]
    assert "/api/groups/activity/comments/{comment_id}" in schema["paths"]
    assert "/api/groups/activity/{activity_id}/recognition" in schema["paths"]
    assert "/api/groups/milestones/{milestone_id}" in schema["paths"]
